version: '2'
services:
  influxdb:
    image: influxdb
    hostname: influxdb
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    labels:
      - "traefik.enable=false"
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana